Push default pages to app(s) in sds
hmcts/azure-shutter-pages pull request #94
Opened 2023-07-25 08:57 UTC by mokainos

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-07-25 09:03 UTC, timja commented on .github/workflows/court-tribunal-hearings.yaml
> +name: push sutter page to court-tribunal-hearings static webapp
```suggestion
name: push shutter page to court-tribunal-hearings static webapp
```

2023-07-25 09:04 UTC, timja commented on .github/workflows/vh-video-web.yaml
> +name: push sutter page to vh-video-web static webapp
```suggestion
name: push shutter page to vh-video-web static webapp
```

2023-07-25 09:29 UTC, timja requested changes

2023-07-25 09:29 UTC, timja commented on .github/workflows/court-tribunal-hearings.yaml
> +name: push shutter page to court-tribunal-hearings static webapp
see https://github.com/hmcts/azure-shutter-pages/pull/94#pullrequestreview-1544985442

2023-07-28 07:33 UTC, JordanHoey96 approved these changes

2023-07-28 08:17 UTC, merged